baseURL = 'http://yuchuan.github.io/'
languageCode = "zh-tw"
title = 'capybara'
theme="PaperMod"
buildDrafts = false 
	
[[menu.main]]
 
identifier = "tags"
 
name = "tags"
 
url = "/tags/"
 
weight = 10

[[menu.main]]
 
identifier = "categories"
 
name = "Categories"
 
url = "/categories/"
 
weight = 20

[[menu.main]]
 
identifier = "archives"
 
name = "Archives"
 
url = "/archives/"
 
weight = 30

 [params.profileMode]
enabled = true
title = "capybara"
subtitle = "capybara capybara capybara"
imageUrl = "https://cdn.britannica.com/79/191679-050-C7114D2B/Adult-capybara.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "capybara"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[params] 
ShowBreadCrumbs = true 
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true

[params.cover]
linkFullImages = true 